name: Publish Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get smart tag
      id: prepare
      uses: Surgo/docker-smart-tag-action@v1
      with:
        docker_image: arma-reforger
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ steps.prepare.outputs.tag }}
